# Generated by Django 3.2.13 on 2022-07-31 06:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='descripton',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='price',
            new_name='age',
        ),
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.TextField(default=django.utils.timezone.now, max_length=34),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='phone',
            field=models.TextField(default=django.utils.timezone.now, max_length=34),
            preserve_default=False,
        ),
    ]
