# Generated by Django 3.2.13 on 2022-07-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0002_auto_20220731_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='confirm_password',
            field=models.TextField(default='', max_length=23),
        ),
        migrations.AddField(
            model_name='students',
            name='password',
            field=models.TextField(default='', max_length=20),
        ),
    ]
