# Generated by Django 3.2.13 on 2022-07-31 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0004_students_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='course',
            field=models.TextField(default='', max_length=10),
        ),
    ]
