# Generated by Django 3.2.13 on 2022-07-31 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0005_students_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='time',
            field=models.TextField(default='', max_length=10),
        ),
    ]
