# Generated by Django 3.2.13 on 2022-07-31 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0009_alter_students_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='phone',
            field=models.CharField(max_length=34),
        ),
    ]
