# Generated by Django 3.2.13 on 2022-08-06 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0012_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='students',
            name='password',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
