# Generated by Django 3.2.13 on 2022-08-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0013_auto_20220806_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='course',
            field=models.TextField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='students',
            name='time',
            field=models.TextField(default='', max_length=25),
        ),
    ]
