# Generated by Django 3.2.13 on 2022-08-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0014_auto_20220806_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=34)),
                ('date', models.DateField(auto_now=True)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
