# Generated by Django 3.2.13 on 2022-08-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0019_programs'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='program_name',
            field=models.CharField(default=2, max_length=25),
            preserve_default=False,
        ),
    ]
