# Generated by Django 3.2.13 on 2022-08-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0024_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='students',
            field=models.CharField(default='users', max_length=3400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignments',
            name='file',
            field=models.FileField(upload_to='assignments/'),
        ),
    ]
