# Generated by Django 3.2.13 on 2022-08-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0026_auto_20220809_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='submitAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=34)),
                ('student', models.CharField(max_length=34)),
                ('file', models.FileField(upload_to='submittedAssignmets/')),
            ],
        ),
    ]
