# Generated by Django 3.2.13 on 2022-08-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0027_submitassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitassignment',
            name='state',
            field=models.CharField(default='', max_length=34),
            preserve_default=False,
        ),
    ]
