# Generated by Django 3.2.13 on 2022-08-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0028_submitassignment_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitassignment',
            name='name',
        ),
        migrations.AddField(
            model_name='submitassignment',
            name='date',
            field=models.DateTimeField(default='2022-08-10 00:17:30.353378'),
            preserve_default=False,
        ),
    ]
