# Generated by Django 3.2.13 on 2022-08-09 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0029_auto_20220809_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitassignment',
            name='date',
        ),
    ]
