# Generated by Django 3.2.13 on 2022-08-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0030_remove_submitassignment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitassignment',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
