# Generated by Django 3.2.13 on 2022-08-09 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0031_submitassignment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitassignment',
            name='date',
        ),
    ]
