# Generated by Django 3.2.13 on 2022-08-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0035_delete_submitassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True)),
                ('student', models.CharField(max_length=34)),
                ('state', models.CharField(max_length=34)),
                ('file', models.FileField(upload_to='submittedAssignmets/')),
            ],
        ),
    ]
