# Generated by Django 3.2.13 on 2022-08-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0036_submitassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='date',
            field=models.DateTimeField(blank=True, default='2022-08-11 11:36:05.319920'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submitassignment',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
