# Generated by Django 3.2.13 on 2022-08-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0039_alter_students_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='students',
            name='time',
            field=models.TextField(default='', max_length=25),
        ),
    ]
