# Generated by Django 3.2.13 on 2022-08-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0040_auto_20220811_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/images/profile.jpg', null=True, upload_to='profile'),
        ),
    ]
