# Generated by Django 3.2.13 on 2022-08-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0041_alter_students_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignments',
            old_name='student',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='attendence',
            old_name='name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='notifications',
            old_name='name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='submitassignment',
            old_name='student',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='students',
            name='profile_pic',
            field=models.ImageField(blank=True, default='media/default/profile.jpg', null=True, upload_to='profile'),
        ),
    ]
