# Generated by Django 3.2.13 on 2022-08-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0042_auto_20220812_0609'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageVehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('fee', models.IntegerField()),
            ],
        ),
    ]
