# Generated by Django 3.2.13 on 2022-08-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0047_programs_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='category',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='programs',
            name='instructor',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
