# Generated by Django 3.2.13 on 2022-08-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0051_auto_20220826_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managevehicles',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
