# Generated by Django 3.2.13 on 2022-08-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0052_alter_managevehicles_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managevehicles',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
